### ISSUE TITLE
Use .f90 suffix instead of .f03

### ISSUE THREAD

**Issue by Beliavsky** [ofmla/OO_fortran_plain_example#1]
I suggesting the .f90 suffix for the source files instead of .f03, since the .f90 suffix means that free source form is used, not that the code conforms to the Fortran 90 standard. Some compilers may not recognize the .f03 suffix, but all recognize .f90.

**Comment by ofmla** [comment]
Thanks for the advice ;) I wrote that example based on an article that used the .f03 suffix, and I ended up bringing that into my code.
